ToonYou:
  base: ""
  path: ""
  video_length: 16
  landmark_video: "/work00/AnimateDiff-adapter-mmv2/debug16/18_The_person_turns_happy_into_happy_ldmks_frames16.mp4"
  motion_module:
    # - "models/Motion_Module/mm_sd_v14.ckpt"
    - "/models00/Motion_Module/mm_sd_v15_v2.ckpt"
    # - "outputs/train_motion_based_adapter_1600_face_512_finetuneV2_16frames-2023-09-26T02-07-12/checkpoints/checkpoint-epoch-1.ckpt"
    # - "outputs/train_motion_based_adapter_1600_face_512_finetuneV2_16frames-2023-09-26T02-07-12/checkpoints/checkpoint-epoch-2.ckpt"
    # - "outputs/train_motion_based_adapter_1600_face_512_finetuneV2_16frames-2023-09-26T02-07-12/checkpoints/checkpoint-epoch-3.ckpt"
    # - "outputs/train_motion_based_adapter_1600_face_512_finetuneV2_16frames-2023-09-26T02-07-12/checkpoints/checkpoint-epoch-4.ckpt"
    # - "outputs/train_motion_based_adapter_1600_face_512_finetuneV2_16frames-2023-09-26T02-07-12/checkpoints/checkpoint-epoch-5.ckpt"
    # - "outputs/train_motion_based_adapter_1600_face_512_finetuneV2_16frames-2023-09-26T02-07-12/checkpoints/checkpoint-epoch-6.ckpt"
    # - "outputs/train_motion_based_adapter_1600_face_512_finetuneV2_16frames-2023-09-26T02-07-12/checkpoints/checkpoint-epoch-7.ckpt"
    # - "outputs/train_motion_based_adapter_1600_face_512_finetuneV2_16frames-2023-09-26T02-07-12/checkpoints/checkpoint-epoch-8.ckpt"
    # - "outputs/train_motion_based_adapter_1600_face_512_finetuneV2_16frames-2023-09-26T02-07-12/checkpoints/checkpoint-epoch-10.ckpt"
    # - "outputs/train_motion_based_adapter_1600_face_512_finetuneV2_16frames-2023-09-26T02-07-12/checkpoints/checkpoint-epoch-12.ckpt"
    # - "outputs/train_motion_based_adapter_1600_face_512_finetuneV2_16frames-2023-09-26T02-07-12/checkpoints/checkpoint-epoch-14.ckpt"
    # - "outputs/train_motion_based_adapter_1600_face_512_finetuneV2_16frames-2023-09-26T02-07-12/checkpoints/checkpoint-epoch-16.ckpt"
    # - "outputs/train_motion_based_adapter_1600_face_512_finetuneV2_16frames-2023-09-26T02-07-12/checkpoints/checkpoint-epoch-18.ckpt"
    # - "outputs/train_motion_based_adapter_1600_face_512_finetuneV2_16frames-2023-09-26T02-07-12/checkpoints/checkpoint-epoch-20.ckpt"

  adapter_module: "/work00/AnimateDiff-adapter-mmv2/outputs/train_adapter_new_dataset_512_16_stride1_ldmk-2023-09-25T13-59-00/checkpoints/checkpoint-epoch-2800.ckpt"

  seed:           [42,42,98376542]
  # [10788741199826055526, 6520604954829636163, 6519455744612555650, 16372571278361863751,
                  
  steps:          25
  guidance_scale: 7.5

  prompt:
    # - "best quality, masterpiece, 1girl, looking at viewer, blurry background, upper body, contemporary, dress, turns into smile"
    # - "masterpiece, best quality, 1girl, solo, cherry blossoms, hanami, pink flower, white flower, spring season, wisteria, petals, flower, plum blossoms, outdoors, falling petals, white hair, black eyes, dress, turns into smile"
    # - "best quality, masterpiece, 1boy, formal, abstract, looking at viewer, masculine, marble pattern, dress, turns into smile"
    # - "best quality, masterpiece, 1girl, cloudy sky, dandelion, contrapposto, alternate hairstyle, dress, turns into smile"
    - "a person is happy."
    - "a person is sad."
    - "The person is sad, High detailed, High precision, Hyper quality, Fine luster, UHD,16k, masterpiece, 1 woman, 1 woman, 1 woman, 1 woman, asian, asian, asianm female, female, female, pure yellow background, business photo, business photo style, half body shot, beautiful face, front view, grey suit, business, business, {best quaility, masterpiece, ultra-realistic}"


  n_prompt:
    # - ""
    # - "badhandv4,easynegative,ng_deepnegative_v1_75t,verybadimagenegative_v1.3, bad-artist, bad_prompt_version2-neg, teeth"
    # - ""
    # - ""
    - ""
    - ""
    - "(worst quality, low quality, bad_pictures, negative_hand-neg:1.2), (shadow on the background:1.3), rendered, 3d"

