liuyifei:
  base: "/models00/DreamBooth_LoRA/majicmixRealistic_v6.safetensors"
  path: "/models00/DreamBooth_LoRA/liuyifei.safetensors"

  inference_config: "configs/inference/inference-v2.yaml"
  
  lora_alpha: 0.5  # 或者 0.5
  motion_module:
    # - "outputs/train_smile_face_512-2023-08-24T12-20-17_epoch126.ckpt"
    - "/models00/Motion_Module/mm_sd_v15_v2.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512-2023-08-31T13-30-42/checkpoints/checkpoint-epoch-500.ckpt"
    - "outputs/train_motion_based_adapter_jsondataset_512_finetuneV2_16frames-2023-09-17T16-02-04/checkpoints/checkpoint-epoch-2.ckpt"
    - "outputs/train_motion_based_adapter_jsondataset_512_finetuneV2_16frames-2023-09-17T16-02-04/checkpoints/checkpoint-epoch-4.ckpt"
    - "outputs/train_motion_based_adapter_jsondataset_512_finetuneV2_16frames-2023-09-17T16-02-04/checkpoints/checkpoint-epoch-6.ckpt"
    - "outputs/train_motion_based_adapter_jsondataset_512_finetuneV2_16frames-2023-09-17T16-02-04/checkpoints/checkpoint-epoch-8.ckpt"
    - "outputs/train_motion_based_adapter_jsondataset_512_finetuneV2_16frames-2023-09-17T16-02-04/checkpoints/checkpoint-epoch-10.ckpt"
    - "outputs/train_motion_based_adapter_jsondataset_512_finetuneV2_16frames-2023-09-17T16-02-04/checkpoints/checkpoint-epoch-12.ckpt"
    - "outputs/train_motion_based_adapter_jsondataset_512_finetuneV2_16frames-2023-09-17T16-02-04/checkpoints/checkpoint-epoch-14.ckpt"
    # 用 1 卡训出来的 ckpt
    # - "/data00/fsq/AnimateDiff-adapter-mmv2/outputs/train_motion_based_adapter_smile_face_512_finetuneV2-2023-09-14T08-30-36/checkpoints/checkpoint-epoch-2.ckpt"
    # - "/data00/fsq/AnimateDiff-adapter-mmv2/outputs/train_motion_based_adapter_smile_face_512_finetuneV2-2023-09-14T08-30-36/checkpoints/checkpoint-epoch-4.ckpt"
    # - "/data00/fsq/AnimateDiff-adapter-mmv2/outputs/train_motion_based_adapter_smile_face_512_finetuneV2-2023-09-14T08-30-36/checkpoints/checkpoint-epoch-6.ckpt"
    # - "/data00/fsq/AnimateDiff-adapter-mmv2/outputs/train_motion_based_adapter_smile_face_512_finetuneV2-2023-09-14T08-30-36/checkpoints/checkpoint-epoch-8.ckpt"
    # - "/data00/fsq/AnimateDiff-adapter-mmv2/outputs/train_motion_based_adapter_smile_face_512_finetuneV2-2023-09-14T08-30-36/checkpoints/checkpoint-epoch-10.ckpt"
    # - "/data00/fsq/AnimateDiff-adapter-mmv2/outputs/train_motion_based_adapter_smile_face_512_finetuneV2-2023-09-14T08-30-36/checkpoints/checkpoint-epoch-12.ckpt"
    # - "/data00/fsq/AnimateDiff-adapter-mmv2/outputs/train_motion_based_adapter_smile_face_512_finetuneV2-2023-09-14T08-30-36/checkpoints/checkpoint-epoch-14.ckpt"
    # - "/data00/fsq/AnimateDiff-adapter-mmv2/outputs/train_motion_based_adapter_smile_face_512_finetuneV2-2023-09-14T08-30-36/checkpoints/checkpoint-epoch-16.ckpt"
    # - "/data00/fsq/AnimateDiff-adapter-mmv2/outputs/train_motion_based_adapter_smile_face_512_finetuneV2-2023-09-14T08-30-36/checkpoints/checkpoint-epoch-18.ckpt"
    # - "/data00/fsq/AnimateDiff-adapter-mmv2/outputs/train_motion_based_adapter_smile_face_512_finetuneV2-2023-09-14T08-30-36/checkpoints/checkpoint-epoch-20.ckpt"
    # - "/data00/fsq/AnimateDiff-adapter-mmv2/outputs/train_motion_based_adapter_smile_face_512_finetuneV2-2023-09-14T08-30-36/checkpoints/checkpoint-epoch-22.ckpt"

    
  adapter_module: "/work00/AnimateDiff-adapter-mmv2/outputs/train_adapter_jsondataset_512_16_stride1_ldmk_crop_ddp-2023-09-17T02-48-19/checkpoints/checkpoint-epoch-35.ckpt"

  seed:           10788741199826055526
                  
  steps:          50
  guidance_scale: 7.5

  prompt:
    - "a person is smiling"
    - "a person is smiling, High detailed, High precision, Hyper quality, Fine luster, UHD,16k, masterpiece, 1 woman, 1 woman, 1 woman, 1 woman, asian, asian, asian female, female, female, beautiful face, pure blue background ,bright, ID photo, identfication photo style, half body shot, front view, white T-shirt, (beautiful eyes), big eyes"
    - "(8k, RAW photo, best quality, masterpiece:1.2), (realistic, photo-realistic:1.37), ultra-detailed, 1 girl,cute, solo,beautiful detailed sky,detailed luxury hotel ,night,sitting,dating,(nose blush),(smile:1.1),(closed mouth) (small breasts:1.33),beautiful detailed eyes,(collared shirt:1.1), bowtie,pleated skirt,(long hair:1.2),floating hair <lora:shirtliftALORAFor_shirtliftv1:0.6>, (no bra:1.33), masterpiece, (((best quality))), ray tracing, floating hair, bokeh, detailed face, detailed eyes, pureerosface_v1 <lora:lora-hanfugirl-v1-5:0.6>"

  n_prompt:
    - ""
    - "(worst quality, low quality, bad_pictures, negative_hand-neg:1.2), (shadow on the background:1.3), rendered, 3d"
    - "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry,"
  random_seed:
  - 10788741199826055526
