yangmi:
  base: "/data00/models/DreamBooth_LoRA/majicmixRealistic_v6.safetensors"
  path: "/data00/models/DreamBooth_LoRA/yangmi_v4.safetensors"

  inference_config: "configs/inference/inference-v2.yaml"
  
  lora_alpha: 0.5
  motion_module:
    - "/data00/fsq/AnimateDiff-adapter-mmv2/outputs/train_motion_based_adapter_smile_face_512_finetuneV2-2023-09-14T15-06-52/checkpoints/checkpoint-epoch-2.ckpt"
    - "/data00/fsq/AnimateDiff-adapter-mmv2/outputs/train_motion_based_adapter_smile_face_512_finetuneV2-2023-09-14T15-06-52/checkpoints/checkpoint-epoch-10.ckpt"
    - "/data00/fsq/AnimateDiff-adapter-mmv2/outputs/train_motion_based_adapter_smile_face_512_finetuneV2-2023-09-14T15-06-52/checkpoints/checkpoint-epoch-18.ckpt"
    - "/data00/fsq/AnimateDiff-adapter-mmv2/outputs/train_motion_based_adapter_smile_face_512_finetuneV2-2023-09-14T15-06-52/checkpoints/checkpoint-epoch-26.ckpt"
    - "/data00/fsq/AnimateDiff-adapter-mmv2/outputs/train_motion_based_adapter_smile_face_512_finetuneV2-2023-09-14T15-06-52/checkpoints/checkpoint-epoch-30.ckpt"
    - "/data00/fsq/AnimateDiff-adapter-mmv2/outputs/train_motion_based_adapter_smile_face_512_finetuneV2-2023-09-14T15-06-52/checkpoints/checkpoint-epoch-50.ckpt"

  adapter_module: "/data00/llz_work/AnimateDiff-adapter/outputs/train_smile_face_512_adapter-2023-08-31T11-10-04/checkpoints/checkpoint-epoch-500.ckpt"

  seed:           10788741199826055526
                  
  steps:          50
  guidance_scale: 7.5

  prompt:
    - "a person is smiling"
    - "a person is smiling, High detailed, High precision, Hyper quality, Fine luster, UHD,16k, masterpiece, 1 woman, 1 woman, 1 woman, 1 woman, asian, asian, asian female, female, female, beautiful face, pure blue background ,bright, ID photo, identfication photo style, half body shot, front view, white T-shirt, (beautiful eyes), big eyes"
    - "(8k, RAW photo, best quality, masterpiece:1.2), (realistic, photo-realistic:1.37), ultra-detailed, 1 girl,cute, solo,beautiful detailed sky,detailed luxury hotel ,night,sitting,dating,(nose blush),(smile:1.1),(closed mouth) (small breasts:1.33),beautiful detailed eyes,(collared shirt:1.1), bowtie,pleated skirt,(long hair:1.2),floating hair <lora:shirtliftALORAFor_shirtliftv1:0.6>, (no bra:1.33), masterpiece, (((best quality))), ray tracing, floating hair, bokeh, detailed face, detailed eyes, pureerosface_v1 <lora:lora-hanfugirl-v1-5:0.6>"

  n_prompt:
    - ""
    - "(worst quality, low quality, bad_pictures, negative_hand-neg:1.2), (shadow on the background:1.3), rendered, 3d"
    - "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry,"
  random_seed:
  - 10788741199826055526
