FilmVelvia:
  base: "/models00/DreamBooth_LoRA/leosamsMoonfile_filmGrain20.safetensors"
  path: "/models00/DreamBooth_LoRA/mj_loras/44_0-000010.safetensors"
  lora_alpha: 1.0
  motion_module:
    - "outputs/train_smile_face_512-2023-08-24T12-20-17_epoch126.ckpt"
    - "/models00/Motion_Module/mm_sd_v15.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512-2023-08-31T13-30-42/checkpoints/checkpoint-epoch-500.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-2.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-10.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-18.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-26.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-34.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-42.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-50.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-58.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-66.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-74.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-82.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-90.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-100.ckpt"

    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-2.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-4.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-6.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-8.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-10.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-12.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-14.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-16.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-18.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-20.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-22.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-24.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-26.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-28.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-30.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-32.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-34.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-36.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-18.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-20.ckpt"
  adapter_module: "outputs/train_smile_face_512_adapter-2023-08-31T11-10-04/checkpoints/checkpoint-epoch-500.ckpt"
  # adapter_module: outputs/train_adapter_emotionalgif_smile_512_8_stride1_ldmk_faceparsing_crop_ddp-2023-09-07T11-06-56/checkpoints/checkpoint-epoch-500.ckpt


  seed:           19386161936
  steps:          27
  guidance_scale: 7.5

  prompt:
    - "a person is smiling, High detailed, High precision, Hyper quality, Fine luster, UHD,16k, masterpiece, 1 woman, 1 woman, 1 woman, 1 woman, asian, asian, asian female, female, female, beautiful face, pure blue background ,bright, ID photo, identfication photo style, half body shot, front view, white T-shirt, (beautiful eyes), big eyes"
  n_prompt:
    -  "(worst quality, low quality, bad_pictures, negative_hand-neg:1.2), (shadow on the background:1.3), rendered, 3d"

# no tie Steps: 27, Sampler: DPM++ 2M Karras, CFG scale: 7, 