FilmVelvia:
  # base: "models/DreamBooth_LoRA/majicmixRealistic_v4.safetensors"
  base: "models/DreamBooth_LoRA/majicmixRealistic_v6.safetensors"
  path: "models/DreamBooth_LoRA/mj_loras/model-000016.safetensors"
  lora_alpha: 0.5
  motion_module:
    - "outputs/train_smile_face_512-2023-08-24T12-20-17_epoch126.ckpt"
    - "models/Motion_Module/mm_sd_v15.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512-2023-08-31T13-30-42/checkpoints/checkpoint-epoch-500.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-2.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-10.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-18.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-26.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-34.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-42.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-50.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-58.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-66.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-74.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-82.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-90.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-2.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-4.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-6.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-8.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-10.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-12.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-14.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-16.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-18.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-20.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-22.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-24.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-26.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-28.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-30.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-32.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-34.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-36.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-18.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512_finetune-2023-09-12T02-40-23/checkpoints/checkpoint-epoch-20.ckpt"
  adapter_module: "outputs/train_smile_face_512_adapter-2023-08-31T11-10-04/checkpoints/checkpoint-epoch-500.ckpt"
  # adapter_module: outputs/train_adapter_emotionalgif_smile_512_8_stride1_ldmk_faceparsing_crop_ddp-2023-09-07T11-06-56/checkpoints/checkpoint-epoch-500.ckpt


  seed:           3919031082
  steps:          25
  guidance_scale: 7.5

  prompt:
    - "a person is smiling, simple_background, red_background, 1girl is happy, portrait, upper body, blonde_hair, bangs, beautiful face, cute, beautiful woman, green_eyes, black tutleneck sweater, lora:add_detail:0.2 lora:FilmVelvia3:0.3"

  n_prompt:
    - "uneven eyes, lazy eye, easynegative,ng_deepnegative_v1_75t, badhandv4,(worst quality:2),(low quality:2),(normal quality:2),lowres,bad anatomy,bad hands,normal quality,((monochrome)),((grayscale)),((watermark))"
