ToonYou:
  base: "models/DreamBooth_LoRA/leosamsMoonfile_filmGrain20.safetensors"
  path: "models/DreamBooth_LoRA/cz-000041.safetensors"
  lora_alpha: 1.0
  motion_module:
    - "models/Motion_Module/mm_sd_v15.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512-2023-08-31T13-30-42/checkpoints/checkpoint-epoch-500.ckpt"
    - "outputs/train_smile_face_512-2023-08-24T12-20-17_epoch126.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512-2023-08-31T13-30-42/checkpoints/checkpoint-epoch-400.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512-2023-08-31T13-30-42/checkpoints/checkpoint-epoch-350.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512-2023-08-31T13-30-42/checkpoints/checkpoint-epoch-300.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512-2023-08-31T13-30-42/checkpoints/checkpoint-epoch-250.ckpt"
    # - "outputs/train_motion_based_adapter_smile_face_512-2023-08-31T13-30-42/checkpoints/checkpoint-epoch-200.ckpt"

  adapter_module: "outputs/train_smile_face_512_adapter-2023-08-31T11-10-04/checkpoints/checkpoint-epoch-500.ckpt"
  
  seed:           42
  # 1921892841
  # [10788741199826055526, 6520604954829636163, 6519455744612555650, 16372571278361863751,
                  
  steps:          27
  guidance_scale: 7.5

  prompt:
    - "a scs man is smiling, upper body, gray suit, black tie, (ciematic light), (bright tone:1.5), gray background, clean background"
    # - "a scs man is smiling, upper body, gray suit, black tie, (ciematic light), gray background"

  n_prompt:
    - "uneven eyes, lazy eye, easynegative,ng_deepnegative_v1_75t, badhandv4,(worst quality:2),(low quality:2),(normal quality:2),lowres,bad anatomy,bad hands,normal quality,((monochrome)),((grayscale)),((watermark)), (shadow:2), top light, moisture, sweat, (transparent:2), (perspective:2), (wrinkle:1.2), (clothes folds:1.5), coat, jacket, (beard:2), (mustache:2)"
    # - "uneven eyes, lazy eye, easynegative,ng_deepnegative_v1_75t, badhandv4,(worst quality:2),(low quality:2),(normal quality:2),lowres,bad anatomy,bad hands,normal quality,((monochrome)),((grayscale)),((watermark)), (shadow:2), top light, moisture, sweat, (transparent:2), (perspective:2), (wrinkle:1.2), (clothes folds:1.5), coat, jacket, (beard:2), (mustache:2)"

