ToonYou:
  base: ""
  path: ""
  motion_module:
    - "outputs/train_motion_based_adapter_smile_face_512-2023-08-31T13-30-42/checkpoints/checkpoint-epoch-60.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512-2023-08-31T13-30-42/checkpoints/checkpoint-epoch-50.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512-2023-08-31T13-30-42/checkpoints/checkpoint-epoch-40.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512-2023-08-31T13-30-42/checkpoints/checkpoint-epoch-30.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512-2023-08-31T13-30-42/checkpoints/checkpoint-epoch-20.ckpt"
    - "outputs/train_motion_based_adapter_smile_face_512-2023-08-31T13-30-42/checkpoints/checkpoint-epoch-10.ckpt"
  adapter_module: "outputs/train_smile_face_512_adapter-2023-08-31T11-10-04/checkpoints/checkpoint-epoch-150.ckpt"

  seed:           42
  # 1921892841
  # [10788741199826055526, 6520604954829636163, 6519455744612555650, 16372571278361863751,
                  
  steps:          25
  guidance_scale: 7.5

  prompt:
    # - "1girl, upper body, beautiful face, straight hair, long hair, gray suit, black tie, (ciematic light), (bright tone:1.5), gray background, <lora:38:1>"
    # - "1girl is smiling, upper body, beautiful face, straight hair, long hair, gray suit, black tie, (ciematic light), (bright tone:1.5), gray background, <lora:38:1>"
    # - "a person is smiling, upper body, beautiful face,  straight hair, long hair, gray suit, black tie, (ciematic light), (bright tone:1.5), gray background, <lora:38:1>"
    - "a person is smiling."

  n_prompt:
    # - "(worst quality, low quality, bad_pictures, negative_hand-neg:1.2), breast, nsfw"
    # - "(worst quality, low quality, bad_pictures, negative_hand-neg:1.2), breast, nsfw"
    # - "(worst quality, low quality, bad_pictures, negative_hand-neg:1.2), breast, nsfw"
    # - "(worst quality, low quality, bad_pictures, negative_hand-neg:1.2), breast, nsfw"

