FilmVelvia:
  base: /data00/models/DreamBooth_LoRA/leosamsMoonfile_filmGrain20.safetensors
  path: #lora_path

  inference_config: "configs/inference/inference-v2.yaml"

  lora_alpha: 0.5
  motion_module:
  # - "/data00/fsq/FacialVideoGeneration_fsq/outputs/train_motion_deca-2023-10-17T00-54-44/checkpoints/checkpoint-epoch-15.ckpt"
  # - "/data00/fsq/FacialVideoGeneration_fsq/outputs/train_motion_deca-2023-10-17T00-54-44/checkpoints/checkpoint-epoch-18.ckpt"
  # - "/data00/fsq/FacialVideoGeneration_fsq/outputs/train_motion_deca-2023-10-17T00-54-44/checkpoints/checkpoint-epoch-20.ckpt"
  # - "/data00/fsq/FacialVideoGeneration_fsq/outputs/train_motion_deca-2023-10-17T00-54-44/checkpoints/checkpoint-epoch-22.ckpt"
  # - "/data00/fsq/FacialVideoGeneration_fsq/outputs/train_motion_deca-2023-10-17T00-54-44/checkpoints/checkpoint-epoch-25.ckpt"
  # - "/data00/fsq/FacialVideoGeneration_fsq/outputs/train_motion_deca-2023-10-17T00-54-44/checkpoints/checkpoint-epoch-28.ckpt"
  # - "/data00/fsq/FacialVideoGeneration_fsq/outputs/train_motion_deca-2023-10-17T00-54-44/checkpoints/checkpoint-epoch-30.ckpt"
  # - "/data00/fsq/FacialVideoGeneration_fsq/outputs/train_motion_deca-2023-10-17T00-54-44/checkpoints/checkpoint-epoch-35.ckpt"
  # - "/data00/fsq/FacialVideoGeneration_fsq/outputs/train_motion_deca-2023-10-17T00-54-44/checkpoints/checkpoint-epoch-40.ckpt"
  - "/data00/bzd/FacialVideoGeneration/llz_checkpoints/checkpoint-epoch-40.ckpt"
  - "/data00/bzd/FacialVideoGeneration/llz_checkpoints/checkpoint-epoch-80.ckpt"
  - "/data00/bzd/FacialVideoGeneration/llz_checkpoints/checkpoint-epoch-120.ckpt"
  - "/data00/bzd/FacialVideoGeneration/llz_checkpoints/checkpoint-epoch-160.ckpt"
  - "/data00/bzd/FacialVideoGeneration/llz_checkpoints/checkpoint-epoch-170.ckpt"




  motion_module_in_tos: false

  adapter_module: "s3://ljj-sh/work/llz_work/FacialVideoGeneration/outputs/train_adapter_render_5600_deca_v231023_512_vilid256_from_scratch-2023-10-24T15-28-04/checkpoints/checkpoint-epoch-1800.ckpt"
  
  adapter_module_in_tos: true
  adapter_cin: 128
  con1_wo_texture: true
  con2_texture: true
  con3_depth: false
  deca_replace: true


  seed: 98376542
  steps: 27
  guidance_scale: 7.5
  prompt:
  - a person is smiling, High detailed, High precision, Hyper quality, Fine luster,
    UHD,16k, masterpiece, 1 woman, 1 woman, 1 woman, 1 woman, asian, asian, asianm
    female, female, female, pure yellow background, business photo, business photo
    style, half body shot, beautiful face, front view, grey suit, business, business,
    {best quaility, masterpiece, ultra-realistic}
  n_prompt:
  - (worst quality, low quality, bad_pictures, negative_hand-neg:1.2), (shadow on
    the background:1.3), rendered, 3d
  random_seed:
  - 98376542
  total_length: 16
  window_size: 1

  val_data_prefix: "stickers_templates_result/"  # 模板的位置

  video_id: 1
  start_f_idx: 0
  video_length: 15
  frame_stride: 1
  lora_id: "emma1"

  


  

