FilmVelvia:
  base: /data00/models/DreamBooth_LoRA/leosamsMoonfile_filmGrain20.safetensors
  path: /data00/models/DreamBooth_LoRA/mj_loras/38_0-000010.safetensors

  inference_config: "configs/inference/inference-v2.yaml"

  lora_alpha: 0.5
  motion_module:
  - "s3://ljj-sh/checkpoints/fansunqi/FacialVideoGeneration/outputs/train_motion_deca-2023-10-17T00-54-44/checkpoints/checkpoint-epoch-15.ckpt"
  - "s3://ljj-sh/checkpoints/fansunqi/FacialVideoGeneration/outputs/train_motion_deca-2023-10-17T00-54-44/checkpoints/checkpoint-epoch-18.ckpt"
  - "s3://ljj-sh/checkpoints/fansunqi/FacialVideoGeneration/outputs/train_motion_deca-2023-10-17T00-54-44/checkpoints/checkpoint-epoch-20.ckpt"
  - "s3://ljj-sh/checkpoints/fansunqi/FacialVideoGeneration/outputs/train_motion_deca-2023-10-17T00-54-44/checkpoints/checkpoint-epoch-22.ckpt"
  - "s3://ljj-sh/checkpoints/fansunqi/FacialVideoGeneration/outputs/train_motion_deca-2023-10-17T00-54-44/checkpoints/checkpoint-epoch-25.ckpt"
  - "s3://ljj-sh/checkpoints/fansunqi/FacialVideoGeneration/outputs/train_motion_deca-2023-10-17T00-54-44/checkpoints/checkpoint-epoch-28.ckpt"
  - "s3://ljj-sh/checkpoints/fansunqi/FacialVideoGeneration/outputs/train_motion_deca-2023-10-17T00-54-44/checkpoints/checkpoint-epoch-30.ckpt"
  - "s3://ljj-sh/checkpoints/fansunqi/FacialVideoGeneration/outputs/train_motion_deca-2023-10-17T00-54-44/checkpoints/checkpoint-epoch-35.ckpt"
  - "s3://ljj-sh/checkpoints/fansunqi/FacialVideoGeneration/outputs/train_motion_deca-2023-10-17T00-54-44/checkpoints/checkpoint-epoch-40.ckpt"
  motion_module_in_tos: true

  adapter_module: "s3://ljj-sh/checkpoints/fansunqi/FacialVideoGeneration/outputs/train_adapter_new_dataset_512_16_stride1_deca-2023-10-16T07-31-51/checkpoints/checkpoint-epoch-1000.ckpt"
  adapter_module_in_tos: true
  adapter_cin: 384
  con1_wo_texture: false
  con2_texture: true
  con3_depth: true
  deca_replace: true


  seed: 98376542
  steps: 27
  guidance_scale: 7.5
  prompt:
  - a person is smiling, High detailed, High precision, Hyper quality, Fine luster,
    UHD,16k, masterpiece, 1 woman, 1 woman, 1 woman, 1 woman, asian, asian, asianm
    female, female, female, pure yellow background, business photo, business photo
    style, half body shot, beautiful face, front view, grey suit, business, business,
    {best quaility, masterpiece, ultra-realistic}
  n_prompt:
  - (worst quality, low quality, bad_pictures, negative_hand-neg:1.2), (shadow on
    the background:1.3), rendered, 3d
  random_seed:
  - 98376542
  total_length: 16
  window_size: 1

  val_data_prefix: "reference/"  # 模板的位置

  # video_id: 2675511
  # start_f_idx: 0
  # video_length: 15
  # frame_stride: 1

  # video_id: 2790140
  # start_f_idx: 80
  # video_length: 15
  # frame_stride: 3

  # video_id: 2795383
  # start_f_idx: 80
  # video_length: 15
  # frame_stride: 3

  video_id: 3139875 # 这个模板非常好
  start_f_idx: 0
  video_length: 15
  frame_stride: 1

  # video_id: 3189294 # 这个模板可能有问题
  # start_f_idx: 0
  # video_length: 58
  # frame_stride: 2

  # video_id: 3205789
  # start_f_idx: 0
  # video_length: 15
  # frame_stride: 3

  # video_id: 3252290
  # start_f_idx: 0
  # video_length: 15
  # frame_stride: 3

  # video_id: 3253738
  # start_f_idx: 0
  # video_length: 15
  # frame_stride: 1 # 3

  # video_id: 3327808
  # start_f_idx: 0
  # video_length: 15
  # frame_stride: 3

  # video_id: 3402898  # 这个模板抖动比较厉害
  # start_f_idx: 0
  # video_length: 15
  # frame_stride: 3

  # video_id: 3249455
  # start_f_idx: 250
  # video_length: 15
  # frame_stride: 2

  # video_id: 10071570
  # start_f_idx: 180 # 200
  # video_length: 15
  # frame_stride: 2 # 1


  

