image_finetune: true

output_dir: "outputs"
pretrained_model_path: "runwayml/stable-diffusion-v1-5"
unet3d_pretrained_model_path: '/huggingface00/hub/models--runwayml--stable-diffusion-v1-5/snapshots/c9ab35ff5f2c362e9e22fbafe278077e196057f0'
pretrained_adapter: '/work00/AnimateDiff-adapter/outputs/train_smile_face_512_adapter-2023-08-31T11-10-04/checkpoints/checkpoint-epoch-500.ckpt'

unet_additional_kwargs:
  use_motion_module              : false
  motion_module_resolutions      : [ 1,2,4,8 ]
  unet_use_cross_frame_attention : false
  unet_use_temporal_attention    : false

  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads                : 8
    num_transformer_block              : 1
    attention_block_types              : [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding         : true
    temporal_position_encoding_max_len : 24
    temporal_attention_dim_div         : 1
    zero_initialize                    : true

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

data_class:         "CelebvText"
train_data:
  meta_path:        "/dataset00/Videos/CelebV-Text/descripitions/filelist.txt"
  data_dir:         "/dataset00/Videos/CelebV-Text/videos/celebvtext_6"
  resolution:       [512,512]
  frame_stride:     1
  video_length:     16

num_workers: 32

validation_data:
  prompts:
    - "This man has a surprised face."
    - "she has a neutral face, and she then turns happy."
    - "This male starts with a face of anger, and he then turns into an happy expression."
    - "this female remains an expression of happiness."
    - "This man has a sad face."
    - "he turns into a disgust expression."
    - "This male starts with a face of contempt, and he then turns into an happy expression."
    - "this female remains an expression of fear."
  num_inference_steps: 25
  guidance_scale: 8.

trainable_modules:
  - "motion_modules."

unet_checkpoint_path: ""

learning_rate:    1.e-4
train_batch_size: 48

max_train_epoch:      100
max_train_steps:      -1
checkpointing_epochs: -1
checkpointing_steps:  100

validation_steps:       100
validation_steps_tuple: [2, 50]

global_seed: 42
mixed_precision_training: true
enable_xformers_memory_efficient_attention: True

is_debug: False
